import { createColumns } from "../../../shared/helpers/commonColumns.helper";

export const fieldTitles = createColumns([
  "id",
  "dob",
  "gender",
  "billing_class",
  "patient_id",
  "line",
  "dos_from",
  "code",
  "units",
  "charges",
  "allowed",
  "benefit",
  "copay",
  "revcode",
  "rend_provider_id",
  "dx1",
  "dx2",
  "field15",
  "field16",
  "field17",
  "field18",
  "field19",
  "field20",
  "field21",
  "field22",
  "field23",
  "field24",
  "field25",
  "field26",
  "field27",
  "field28",
  "field29",
  "field30",
]);
