export const createColumns = (visibleFields: string[]) => {
  const allColumns = [
    { field: "id", headerName: "ID" },
    { field: "dob", headerName: "Date of Birth" },
    { field: "gender", headerName: "Gender" },
    { field: "billing_class", headerName: "Billing Class" },
    { field: "patient_id", headerName: "Patient ID" },
    { field: "line", headerName: "Line" },
    { field: "dos_from", headerName: "Date of Service" },
    { field: "code", headerName: "Code" },
    { field: "units", headerName: "Units" },
    { field: "charges", headerName: "Charges" },
    { field: "allowed", headerName: "Allowed" },
    { field: "benefit", headerName: "Benefit" },
    { field: "copay", headerName: "Copay" },
    { field: "revcode", headerName: "Revenue Code" },
    { field: "rend_provider_id", headerName: "Rendering Provider ID" },
    { field: "dx1", headerName: "Diagnosis 1" },
    { field: "dx2", headerName: "Diagnosis 2" },
    { field: "field15", headerName: "Field 15" },
    { field: "field16", headerName: "Field 16" },
    { field: "field17", headerName: "Field 17" },
    { field: "field18", headerName: "Field 18" },
    { field: "field19", headerName: "Field 19" },
    { field: "field20", headerName: "Field 20" },
    { field: "field21", headerName: "Field 21" },
    { field: "field22", headerName: "Field 22" },
    { field: "field23", headerName: "Field 23" },
    { field: "field24", headerName: "Field 24" },
    { field: "field25", headerName: "Field 25" },
    { field: "field26", headerName: "Field 26" },
    { field: "field27", headerName: "Field 27" },
    { field: "field28", headerName: "Field 28" },
    { field: "field29", headerName: "Field 29" },
    { field: "field30", headerName: "Field 30" },
  ];

  return allColumns.filter((col) => visibleFields.includes(col.field));
};
